# 快速创建数组

In [1]:
import numpy as np

In [2]:
# 创键一个正态分布的随机数组
np.random.randn(10)

array([-0.60336649,  1.78569326, -0.42572832, -0.77644539, -1.75179803,
       -0.22873261,  1.16474377, -0.16248256,  0.19137333,  0.35854085])

In [6]:
# 创建随机整数的数组
np.random.randint(10)

3

In [7]:
np.random.randint(10, size=[3, 5])  # 创建3行5列 

array([[5, 5, 3, 4, 1],
       [2, 0, 2, 1, 9],
       [4, 6, 3, 3, 8]])

In [8]:
# create 4 rows 5 columns 20 size  num < 10
np.random.randint(10, size=20).reshape(4, 5)

array([[9, 6, 0, 2, 9],
       [0, 1, 5, 7, 6],
       [3, 1, 2, 2, 9],
       [6, 8, 2, 2, 1]])

# 数组的运算

In [9]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [10]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [11]:
a

array([[2, 8, 0, 2, 1],
       [2, 5, 2, 7, 6],
       [4, 0, 3, 4, 1],
       [7, 9, 2, 9, 7]])

In [12]:
b

array([[6, 8, 5, 8, 4],
       [0, 4, 3, 4, 3],
       [6, 6, 9, 8, 9],
       [0, 7, 6, 8, 5]])

In [13]:
a + b

array([[ 8, 16,  5, 10,  5],
       [ 2,  9,  5, 11,  9],
       [10,  6, 12, 12, 10],
       [ 7, 16,  8, 17, 12]])

In [14]:
a * b

array([[12, 64,  0, 16,  4],
       [ 0, 20,  6, 28, 18],
       [24,  0, 27, 32,  9],
       [ 0, 63, 12, 72, 35]])

In [15]:
a - b

array([[-4,  0, -5, -6, -3],
       [ 2,  1, -1,  3,  3],
       [-2, -6, -6, -4, -8],
       [ 7,  2, -4,  1,  2]])

In [42]:
# a / b  # inf 无穷大

In [18]:
# 转换为列表
a.tolist()

[[2, 8, 0, 2, 1], [2, 5, 2, 7, 6], [4, 0, 3, 4, 1], [7, 9, 2, 9, 7]]

In [20]:
# 矩阵
np.mat([[1, 2, 3],
        [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [21]:
np.mat(a)

matrix([[2, 8, 0, 2, 1],
        [2, 5, 2, 7, 6],
        [4, 0, 3, 4, 1],
        [7, 9, 2, 9, 7]])

# 矩阵的运算

In [22]:
A = np.mat(a)
B = np.mat(b)

In [24]:
A

matrix([[2, 8, 0, 2, 1],
        [2, 5, 2, 7, 6],
        [4, 0, 3, 4, 1],
        [7, 9, 2, 9, 7]])

In [25]:
B

matrix([[6, 8, 5, 8, 4],
        [0, 4, 3, 4, 3],
        [6, 6, 9, 8, 9],
        [0, 7, 6, 8, 5]])

In [26]:
A + B

matrix([[ 8, 16,  5, 10,  5],
        [ 2,  9,  5, 11,  9],
        [10,  6, 12, 12, 10],
        [ 7, 16,  8, 17, 12]])

In [27]:
A -B

matrix([[-4,  0, -5, -6, -3],
        [ 2,  1, -1,  3,  3],
        [-2, -6, -6, -4, -8],
        [ 7,  2, -4,  1,  2]])

In [2]:
# A * B

In [30]:
B = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [31]:
B

matrix([[2, 0, 8, 6],
        [1, 3, 4, 4],
        [3, 2, 4, 4],
        [1, 6, 7, 7],
        [9, 6, 9, 3]])

In [32]:
A * B

matrix([[ 23,  42,  71,  61],
        [ 76,  97, 147, 107],
        [ 30,  36,  81,  67],
        [101, 127, 226, 170]])

# Array 的常用函数

In [33]:
a = np.random.randint(20, size=20).reshape(4, 5)

In [34]:
a

array([[ 5, 18, 11, 14, 17],
       [18, 10,  0,  4,  4],
       [ 0,  9,  5, 14,  4],
       [ 3, 17, 10,  0, 14]])

In [35]:
# array 去重
np.unique(a)

array([ 0,  3,  4,  5,  9, 10, 11, 14, 17, 18])

In [36]:
sum(a) # 求每列

array([26, 54, 26, 32, 39])

In [37]:
sum(a[0]) # 求第一行

65

In [38]:
sum(a[:, 0]) # 求第一列

26

In [39]:
a.max() 

18

In [40]:
max(a[0]) # 第一行的最大值

18

In [41]:
max(a[:, 0]) # 求第一列的最大值

18