# 数组的创建和访问

In [1]:
import numpy as np

In [4]:
# create from python list
list_1 = [1, 2, 3, 4]

In [5]:
list_1

[1, 2, 3, 4]

In [6]:
array_1 = np.array(list_1)

In [7]:
array_1

array([1, 2, 3, 4])

In [8]:
list_2 = [1, 2, 3, 4]

In [9]:
array_2 = np.array([list_1, list_2])

In [10]:
array_2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
array_2.shape

(2, 4)

In [14]:
array_2.size

8

In [15]:
array_2.dtype

dtype('int32')

In [16]:
array_3 = np.array([[1.0, 2.3, 4], [5, 6, 7]])

In [17]:
array_3.dtype

dtype('float64')

#### arange 创建数组

In [21]:
array_4 = np.arange(1, 5)

#### 全零数组

In [22]:
array_5 = np.zeros(5)

In [23]:
array_5

array([0., 0., 0., 0., 0.])

In [24]:
# 两行三列 全零数组
array_6 = np.zeros([2, 3])

In [25]:
array_6

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 单位数组

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5).dtype

dtype('float64')

#### 读取数组

In [30]:
a = np.arange(10)

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[5]

5

In [33]:
a[3: 6]

array([3, 4, 5])

In [35]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
b[1][2]

6

In [38]:
b[1, 2]

6

In [39]:
b[:2, 1:2]

array([[2],
       [5]])